version: "3.9"
services:
  web:
    build: .
    ports:
      - "3002:3002"
    depends_on:
      - mongo
    env_file:
      - .env
    volumes:
      - /usr/src/app/node_modules
    command: npm start
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./db/src/app/fec