version: "3.9"
services:
  web:
    build: .
    ports:
      - "3002:3002"
    depends_on:
      - mongo
    env_file:
      - .env
    environment:
      - PORT=${PORT}
      - NODE_ENV=${NODE_ENV}
      - HOST_PRODUCT_SIZE=${HOST_PRODUCT_SIZE}
      - DB_HOST_ENV=${DB_HOST_ENV}
    volumes:
      - /usr/src/app/node_modules
    command: npm start
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./db/src/app/fec